# Site settings
title: Bigroo Hiking Club
author:
  name: Jiakang
  email: h2808118@hotmail.com
description: "Great site about Hiking and amazing views in Australia."

# Build settings

theme: jekyll-theme-tactile
